export {default as Home} from './Home'
export {default as Details} from './Details'
export {default as Settings} from './Settings'
export {default as Perfil} from './Perfil'
export {default as Screen} from './Screen'
export {default as Notification} from './Notification'
